DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS tasks;

CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);
CREATE TABLE tasks(
    id SERIAL PRIMARY KEY, 
    title TEXT NOT NULL,
    done BOOLEAN NOT NULL DEFAULT false,
    user_id INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);